### ISSUE TITLE
Telegram bot registration

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/telegram#1]
```[tasklist]
### Tasks
- [ ] Register a development bot on BotFather
- [x] Register a staging bot on BotFather
- [x] Register a production bot on BotFather
```

**Comment by cyri113** [comment]
Bots:

[@TogetherCrewBot](https://t.me/TogetherCrewBot) - Production
[@TogetherCrewStagingBot](https://t.me/TogetherCrewStagingBot) - Staging

**Comment by cyri113** [comment]
@scientiststwin1 you can create a development one for yourself.
