### ISSUE TITLE
Basic project setup

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/telegram#2]
```[tasklist]
### Tasks
- [x] Create NestJS application
- [x] Create Dockerfile (see discourse project)
- [x] Create docker-compose.dev.yml (see discourse project)
- [x] Configure environment variables
- [x] Configure linter, tests, etc. (as required)
- [x] Integrate into TogetherCrew GitHub CI/CD (see discourse project)
```
